[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor = "8evHUdVAM5L9DvV8feuSGxFy6Zy62M6N6T6BufrFs6Se"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = '/home/prash/.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"